const fs = require('fs');
const path = require('path');

const html = fs.readFileSync(path.join(__dirname, 'public/index.html'), 'utf8');

// Build a self-contained worker JS
const workerJs = `
// Auto-generated by build.js — do not edit
const HTML = ${JSON.stringify(html)};

async function handleRemoveBg(request, env) {
  const apiKey = env.REMOVE_BG_API_KEY;
  if (!apiKey) return json({ error: "API key not configured" }, 500);
  const maxSize = parseInt(env.MAX_FILE_SIZE || "10485760", 10);
  try {
    const formData = await request.formData();
    const imageFile = formData.get("image");
    const size = formData.get("size") || "auto";
    if (!imageFile) return json({ error: "No image provided" }, 400);
    if (imageFile.size > maxSize) return json({ error: "File too large. Max " + (maxSize/1024/1024) + "MB" }, 400);
    const bg = new FormData();
    bg.append("image_file", imageFile, imageFile.name);
    bg.append("size", size);
    const res = await fetch("https://api.remove.bg/v1.0/removebg", { method: "POST", headers: { "X-Api-Key": apiKey }, body: bg });
    if (!res.ok) {
      const txt = await res.text();
      let msg;
      try { const j = JSON.parse(txt); msg = (j.errors && j.errors[0] && j.errors[0].title) || txt; } catch(e) { msg = "Remove.bg error: " + res.status; }
      if (res.status === 402) return json({ error: "API credits exhausted." }, 503);
      return json({ error: msg }, res.status);
    }
    const blob = await res.blob();
    return new Response(blob, { headers: { "Content-Type": "image/png", "Cache-Control": "no-store" } });
  } catch(e) { return json({ error: e.message || "Server error" }, 500); }
}

function json(data, status) { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json" } }); }

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") return new Response(null, { headers: { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET, POST, OPTIONS", "Access-Control-Allow-Headers": "Content-Type" } });
    const url = new URL(request.url);
    if (url.pathname === "/" || url.pathname === "/index.html") return new Response(HTML, { headers: { "Content-Type": "text/html; charset=utf-8" } });
    if (url.pathname === "/api/remove-bg" && request.method === "POST") return handleRemoveBg(request, env);
    if (url.pathname === "/api/health") return Response.json({ status: "ok" });
    return new Response("Not found", { status: 404 });
  }
};
`;

fs.mkdirSync(path.join(__dirname, 'dist'), { recursive: true });
fs.writeFileSync(path.join(__dirname, 'dist/worker.js'), workerJs);
console.log('✅ Built dist/worker.js (' + workerJs.length + ' bytes)');
