name = "bg-vanish"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
no_bundle = true

[[d1_databases]]
binding = "DB"
database_name = "bg-vanish-db"
database_id = "c4926cbc-f3e7-46fc-ba27-c68fdcc63350"

[vars]
MAX_FILE_SIZE = "10485760"
PAYPAL_CLIENT_ID = "AWGzJFEzcnBduA-it4lcUirsL0o2f5RsexRxiuW3vSO3Jm2loSYQZ1rueQz5KfzaPvh-Nytb-5zs-jYy"
PAYPAL_SECRET = "EKclAtfFMMo-OT0DMyMsaXDANMXlHrhNlo3VEUXX4jpbbLUCggkB4-8PtAdskvt-QXWxVFSsdsf-35S6"
PAYPAL_BASE_URL = "https://api-m.sandbox.paypal.com"
