name = "bg-vanish"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
no_bundle = true

[vars]
MAX_FILE_SIZE = "10485760"

# Set this secret before deploying:
# wrangler secret put REMOVE_BG_API_KEY
